In [4]:
import numpy as np

In [7]:
np.array([1,2,3]) + np.array([1,2,3])

array([2, 4, 6])

In [8]:
np.array([1,2,3]) * 3

array([3, 6, 9])

In [9]:
np.array([1,2,3]) / 1.2

array([ 0.83333333,  1.66666667,  2.5       ])

In [11]:
N_doc = 49387975
N_term = 4151693235
Doc_AVG_Len = N_term/N_doc

import math

In [12]:
def IDF(term_len: int) -> float:
    return math.log((N_doc - term_len + 0.5)/(term_len + 0.5))

def K_BM25(doc_len: int) -> float:
    #0.75 = b
    #0.25 = 1-b
    return 1.2 * (0.25 +  0.75 * doc_len / Doc_AVG_Len )

def BM25(TF: int, K: float, IDF: float) -> float:
    # 2.2 = k1+1
    return IDF * (2.2 * TF) / (K * TF)


In [16]:
term_len = 6

In [18]:
doc_len = np.array([131,12,3312])

In [19]:
tfs = np.array([1,2,5])

In [20]:
BM25(tfs, K_BM25(doc_len), IDF(term_len))

array([ 20.47286781,  81.34777349,   0.97472885])